@Echo off
Echo Step 1 of 4: Activating Virtual Environment...
call "C:\Users\Swastik\Documents\iot_ud_3\iot_ud_3\Scripts\activate.bat"
Echo Step 2 of 4: Referencing and Initiating OpenVino Installtion...
call "C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\bin\setupvars.bat"
Echo Step 3 of 4: Testing Correct Initialisation...
python C:\Users\Swastik\Documents\iot_ud_3\env_test.py
Echo Step 4 of 4: Starting Cursor Controller...
python cursorcontroller.py -f "C:\Users\Swastik\Documents\iot_ud_3\models\intel\face-detection-retail-0005\FP32\face-detection-retail-0005.xml" -p "C:\Users\Swastik\Documents\iot_ud_3\models\intel\head-pose-estimation-adas-0001\FP32\head-pose-estimation-adas-0001.xml" -l "C:\Users\Swastik\Documents\iot_ud_3\models\intel\facial-landmarks-35-adas-0002\FP32\facial-landmarks-35-adas-0002.xml" -g "C:\Users\Swastik\Documents\iot_ud_3\models\intel\gaze-estimation-adas-0002\FP32\gaze-estimation-adas-0002.xml" -i "CAM" --print_layer_metrics True -v True
